### PR TITLE
Closes #3 - Implement capability to export the difference between successive values

### LINKED ISSUE #3: Implement capability to export the difference between successive values
In this ticket, the exporter should be extended to allow the export of the difference between successive values instead of the absolute value. This has the benefit that only values can be exported which are bigger than 0, reducing the data of writing the same value over and over again.

This will break the Prometheus style metric collection where only sums and coutners are exposed.

### PR DESCRIPTION
**Pull request by mariusoe**
This change is [Reviewable](https://reviewable.io/reviews/novatecconsulting/opencensus-influx-exporter/5)

### CODE REVIEW

**Review by JonasKunz — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/novatecconsulting/opencensus-influx-exporter/5)* status: all files reviewed, 4 unresolved discussions (waiting on @mariusoe)

___
*[src/main/java/rocks/inspectit/opencensus/influx/InfluxExporter.java, line 106 at r1](https://reviewable.io/reviews/novatecconsulting/opencensus-influx-exporter/5#-M4xMCiN0r1anrmDbIAv:-M4xMCiOBk75oq69QBOB:b-w8qc2v) ([raw file](https://github.com/novatecconsulting/opencensus-influx-exporter/blob/7a41c210870df157094a33473c1292a3f146347e/src/main/java/rocks/inspectit/opencensus/influx/InfluxExporter.java#L106)):*
> ```Java
>      *                     the statistics cache.
>      */
>     private synchronized void export(boolean ignoreInflux) {
> ```

How about naming this parameter `dryRun`, in a git style?
___
*[src/main/java/rocks/inspectit/opencensus/influx/InfluxExporter.java, line 202 at r1](https://reviewable.io/reviews/novatecconsulting/opencensus-influx-exporter/5#-M4xOEfL5VcH8Tv9qQdw:-M4xOEfM-GuXbVAkfyLT:bsowolb) ([raw file](https://github.com/novatecconsulting/opencensus-influx-exporter/blob/7a41c210870df157094a33473c1292a3f146347e/src/main/java/rocks/inspectit/opencensus/influx/InfluxExporter.java#L202)):*
> ```Java
> 
>             Point.Builder totalPoint = Point.measurement(measurementName)
>                     .addField(sumFieldName, sumValue.orElse(DOUBLE_ZERO))
> ```

Here you write zero values even though we said to omit zeros for counters.

How about calling `transformValue` for both values and simply adding them as two points to the `result`?
___
*[src/main/java/rocks/inspectit/opencensus/influx/InfluxExporter.java, line 219 at r1](https://reviewable.io/reviews/novatecconsulting/opencensus-influx-exporter/5#-M4xP6U11iVujK4uRQiN:-M4xP6U11iVujK4uRQiO:b-f6361j) ([raw file](https://github.com/novatecconsulting/opencensus-influx-exporter/blob/7a41c210870df157094a33473c1292a3f146347e/src/main/java/rocks/inspectit/opencensus/influx/InfluxExporter.java#L219)):*
> ```Java
>                 tempTagMap.put("bucket", interval);
> 
>                 Optional<Number> bucketValue = processValue(measurementName, fieldName, tempTagMap, bucket.getCount());
> ```

Same as above, just call your `transformValue` function?
___
*[src/main/java/rocks/inspectit/opencensus/influx/InfluxExporter.java, line 244 at r1](https://reviewable.io/reviews/novatecconsulting/opencensus-influx-exporter/5#-M4xNGy-1iQUsTkPdXER:-M4xNGy-1iQUsTkPdXES:bai6tzz) ([raw file](https://github.com/novatecconsulting/opencensus-influx-exporter/blob/7a41c210870df157094a33473c1292a3f146347e/src/main/java/rocks/inspectit/opencensus/influx/InfluxExporter.java#L244)):*
> ```Java
>      * @return the value to export for the specified metric
>      */
>     private Optional<Number> processValue(String measurementName, String fieldName, Map<String, String> tags, Number value) {
> ```

Shouldn't this method only be called for metrics with type counter?
To me it seems like it called regardless of the type.
___
*[src/main/java/rocks/inspectit/opencensus/influx/StatisticsCache.java, line 48 at r1](https://reviewable.io/reviews/novatecconsulting/opencensus-influx-exporter/5#-M4xPJH5EVv2lh9Uhk7y:-M4xPJH5EVv2lh9Uhk7z:b-ialsv7) ([raw file](https://github.com/novatecconsulting/opencensus-influx-exporter/blob/7a41c210870df157094a33473c1292a3f146347e/src/main/java/rocks/inspectit/opencensus/influx/StatisticsCache.java#L48)):*
> ```Java
>      * @return the key which is used for caching the last metric value
>      */
>     private String cacheKey(String measurementName, String fieldName, Map<String, String> tag) {
> ```

I would not suggest this appraoch for building a unique key.

Just use a lombok `@Value` class with the fields `measurementName`, `fieldName` and `tags`.
Hashcode and equals will work as you expect.

Do not forget to copy the `tags` map! You mutate it for your histogram handling, whic hwould then lead to errors here.

**Review by mariusoe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/novatecconsulting/opencensus-influx-exporter/5)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @JonasKunz)

___
*[src/main/java/rocks/inspectit/opencensus/influx/InfluxExporter.java, line 244 at r1](https://reviewable.io/reviews/novatecconsulting/opencensus-influx-exporter/5#-M4xNGy-1iQUsTkPdXER:-M4y0ZPZ0myU0Z63z8VI:b-e7hqhz) ([raw file](https://github.com/novatecconsulting/opencensus-influx-exporter/blob/7a41c210870df157094a33473c1292a3f146347e/src/main/java/rocks/inspectit/opencensus/influx/InfluxExporter.java#L244)):*
<details><summary><i>Previously, JonasKunz (Jonas Kunz) wrote…</i></summary><blockquote>

Shouldn't this method only be called for metrics with type counter?
To me it seems like it called regardless of the type.
</blockquote></details>

Done. Added also some tests.

**Review by JonasKunz — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/novatecconsulting/opencensus-influx-exporter/5)* status: all files reviewed, 1 unresolved discussion (waiting on @mariusoe)

___
*[src/main/java/rocks/inspectit/opencensus/influx/InfluxExporter.java, line 242 at r2](https://reviewable.io/reviews/novatecconsulting/opencensus-influx-exporter/5#-M4y2Mti-9rAIuXTqsAn:-M4y2MtjBaaWbTNHFKTW:bwf28hi) ([raw file](https://github.com/novatecconsulting/opencensus-influx-exporter/blob/18f2e8ef790f435f378565d6bfe79346d46ff866/src/main/java/rocks/inspectit/opencensus/influx/InfluxExporter.java#L242)):*
> ```Java
>             if (difference.doubleValue() != 0D) {
>                 if (isGauge) {
>                     return Optional.of(value);
> ```

Gauges should always be written, even if they are zero. Also with this implementation you uneccessarily store the gauges in the stats cache.
Just add an early-out to the method if `isGauge` is `true`.

**Review by JonasKunz — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/novatecconsulting/opencensus-influx-exporter/5)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
